#!/bin/csh -f

# the path for Ruby is different on the submit server than on Grace, so
# using "ruby" to invoke the student's program.

set test_number = 15
if (-e `where ruby1.9.1`) then
  set ruby_version = ruby1.9.1
else
  if (-e `where ruby1.8`) then
    set ruby_version = ruby1.8
  else
    set ruby_version = ruby
  endif
endif

$ruby_version public$test_number.rb
